name: carve
description: A dart command line tool for generating file templates needed for flutter application development.
version: 0.0.1
# homepage: https://www.example.com
repository: https://github.com/jksevend/carve

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

executables: 
  carve: main

dependencies: 
  args: ^2.2.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
